version: '3.8'

services:
  spark_single:
    image: jupyter/pyspark-notebook:spark-3.5.0
    container_name: spark_single
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./:/home/jovyan/work
    user: root

  postgres:
    image: postgres:13
    container_name: airflow_db
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  airflow-webserver:
    image: apache/airflow:2.10.2
    container_name: airflow_webserver
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/home/jovyan/work
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=d5157558325e4e3c03de9a085796db0b
      - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8080
      - AIRFLOW__LOGGING__SERVE_LOGS=True
    ports:
      - "8080:8080"
    command: webserver
    user: "${AIRFLOW_UID:-50000}"

  airflow-scheduler:
    image: apache/airflow:2.10.2
    container_name: airflow_scheduler
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/home/jovyan/work
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=d5157558325e4e3c03de9a085796db0b
      - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8080
      - AIRFLOW__LOGGING__SERVE_LOGS=True
    command: scheduler
    user: "${AIRFLOW_UID:-50000}"

  airflow-init:
    image: apache/airflow:2.10.2
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=d5157558325e4e3c03de9a085796db0b
      - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8080
      - AIRFLOW__LOGGING__SERVE_LOGS=True
    command: db migrate
    user: "0"
